### PR TITLE
Subtitle position

### PR DESCRIPTION
**Pull request by buschtoens**
Now 20% more useful.

Why the fuck do I even have to make PRs on my own repo?

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
You don't have to make PRs on your own repo...

**Comment by buschtoens** [comment]
Still awake? :smile: 

I know, but when I merge the branch locally with the GitHub for Windos GUI I don't get those fancy auto-magic "Merge pull request ..." messages. Hm.

But now that you're hear, I'd like to inform you, about a small API change on the badge. We now have the new option `subtitlePos` that defaults to `"bottom"`. When you set it to `"right"` it sets the subtitle to the right.

right

**Comment by ForbesLindesay** [comment]
cool, I can't decide which I prefer.  I'm still awake because I haven't got Jepso-CI to a beta stage yet, it still doesn't record the results of tests and generate pretty browser compatibility badges.

**Comment by buschtoens** [comment]
Hm, I'd help, but it's closed source, isn't it?
Best wishes. Grab a coffee and take short break. Maybe go out for a short walk. Helps me everytime. :)

In the meantime I'll try to simplify the browser logos.

**Comment by ForbesLindesay** [comment]
Yeh, for now the actual site is closed source (I still haven't decided whether it'll remain so). I'm trying to open source anything that could be re-usable for something else.

**Comment by buschtoens** [comment]
That's the spirit! :D

**Pull request merged**
