### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by ForbesLindesay**
Add tests and travis, I've left it up to you to add travis logo to the readme once it's enabled for your copy of the repository

### CODE REVIEW

**Comment by buschtoens** [comment]
Thanks for the tests. :smile:

But we have a [CRLF hell](http://stackoverflow.com/a/1967986/420747). Next time please set `core.autocrlf` to `true`.

**Comment by ForbesLindesay** [comment]
It is set to true...nothing's perfect.

That's partly why I added the regex replacement of `/\r/g` to all the file reads.  I didn't want tests failing on windows just because of stupid line endings.

Out of curiosity, which files ended up with CRLF problems?

**Comment by buschtoens** [comment]
[Plain to see](https://github.com/silvinci/component-badge/pull/2/files). Haha. :D

**Comment by ForbesLindesay** [comment]
I'm confused, where does that show line endings?

**Comment by buschtoens** [comment]
It's the `package.json`, to be exact. You only edited one or two lines an the whole file is recommited.

**Comment by ForbesLindesay** [comment]
Are you sure that's CRLF hell though, and not a problem with tabs/spaces, or equally just the diff algorithm messing up slightly?  It initially completely re-formatted that code when I ran `npm install mocha --save-dev` because npm likes to pick the format for you, and I had to format it back the way you had it in https://github.com/silvinci/component-badge/commit/490c0de758310342b5ea8c7bd42a9f623646a9ab#package.json so all those changes did occur, it's just that because you're looking at the aggregate results it looks like nothing's changed.

**Comment by buschtoens** [comment]
Whoops, you're right. My first idea on a completely recommited file is CRLF hell. It's indeed the tab stuff. But now we have the correct format. Thanks. :)

**Comment by ForbesLindesay** [comment]
:smile: my editor is set up to really avoid tabs like the plague, mostly because that's the way the JS community at large tends to prefer to go (particularly the node.js world) and consistency trumps everything else when it comes to tabs vs. 2 spaces vs. 4 spaces.

**Comment by buschtoens** [comment]
A few months ago i prefered real hard tabs, 4 spaces wide.
Then I saw TJ's coding style and changed two 2 spaces, but still hard tabs.

I like them, since they take one byte less per indent. :D

But if you want to use soft tabs, I can adapt to this as well, since this is mainly your project. :wink:

**Comment by ForbesLindesay** [comment]
I want to use 2 spaces (i.e. soft tabs), but I'm fine with dependencies using whatever, so `component-badge` is your baby, and I'll do my best to adapt to you here, provided you return the favour inside `component-website` :wink:

**Comment by buschtoens** [comment]
Okay, we can do that! Haha. :smiley:

**Pull request merged**
